#!/usr/bin/env bash

# Lead Management System - Getting Started Script
# Run this to understand the setup process

echo "╔═════════════════════════════════════════════════════════════╗"
echo "║     Lead Management System - Getting Started Guide          ║"
echo "╚═════════════════════════════════════════════════════════════╝"
echo ""

echo "📍 Project Location:"
echo "   C:\Users\User\Desktop\Java\lead-management-system"
echo ""

echo "📖 Documentation Files (in order of reading):"
echo "   1. 00-START-HERE.md          ⭐ Start here! (2 min)"
echo "   2. QUICKSTART.md             ⭐ Setup & run (5 min)"
echo "   3. SETUP.md                  Complete guide (15 min)"
echo "   4. TESTING.md                API examples (20 min)"
echo "   5. API-REFERENCE.md          All endpoints (10 min)"
echo "   6. README.md                 Features & tech (10 min)"
echo ""

echo "⚡ Quick Start (copy & paste):"
echo ""
echo "   # Navigate to project"
echo "   cd \"C:\\Users\\User\\Desktop\\Java\\lead-management-system\""
echo ""
echo "   # Install dependencies (one time only)"
echo "   npm run setup"
echo ""
echo "   # Terminal 1: Start backend"
echo "   cd backend && npm run dev"
echo ""
echo "   # Terminal 2: Start frontend"
echo "   cd frontend && npm run dev"
echo ""
echo "   # Then open in browser:"
echo "   http://localhost:3000"
echo ""

echo "🎯 What You Have:"
echo "   ✅ Node.js + Express backend with 7 API endpoints"
echo "   ✅ Next.js + React frontend with 4 pages"
echo "   ✅ SQLite database with 3 tables"
echo "   ✅ Smart duplicate detection algorithm"
echo "   ✅ Complete input validation"
echo "   ✅ Status workflow management"
echo "   ✅ Activity timeline & audit log"
echo "   ✅ Responsive UI with Tailwind CSS"
echo ""

echo "📚 Feature Summary:"
echo "   • Create leads with auto-assignment"
echo "   • List leads with filters & pagination"
echo "   • Update status with validation"
echo "   • Detect duplicate leads intelligently"
echo "   • View activity timeline by date"
echo "   • Manage users & assignments"
echo ""

echo "🔧 Optional: Load Sample Data"
echo "   cd backend && npm run seed"
echo ""

echo "✨ Database Info:"
echo "   • Location: backend/database.sqlite"
echo "   • Engine: SQLite3"
echo "   • Tables: Users, Leads, LeadActivities"
echo ""

echo "🆘 Troubleshooting:"
echo "   • Port issues: See SETUP.md"
echo "   • API not working: Check backend is running"
echo "   • Need help: Read 00-START-HERE.md"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Ready to get started? Open 00-START-HERE.md or QUICKSTART.md"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
